### ISSUE TITLE
Missing File (client_secret)

### ISSUE THREAD

**Issue by ghost** [DevonCrawford/YouTube-Descriptions-Updater#2]

**Comment by RefexHD** [comment]
i found it now on youtube api
here if you need it : 

{
  "installed": {
    "client_id": "client_id",
    "client_secret": "client_secret",
    "redirect_uris": ["http://localhost:8080/oauth2callback"],
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://accounts.google.com/o/oauth2/token"
  }
}
